### ISSUE TITLE
As a Registered cleaner, I will click in the login page to enter in an exclusive area (logged in) to system so that the cleaner can see Cleaner page

### ISSUE THREAD

**Issue by rmc3408** [Comp231-S4G5/OneClickCleaner#14]
- [x] Create link ‘Sign in” in the main menu to redirect to the validation page #126

- [x] Create Validation page to choose the type of user, and the fields to write username and password. #98

- [x] Create error message when credentials are not valid. #114

- [x] Create a function to validate credentials and redirect to the customized Home Page when credentials are valid. #130

- [x] Create customized page that will show: “Sign out” instead of “Sign In” in Main Menu, the Cleaner name in the corner and add new element in the main menu call “Profile” #120
