### ISSUE TITLE
As a Client, I can see the Selected Emergency Service Page so that I can enter my desire duration of the service in order to see the price

### ISSUE THREAD

**Issue by rmc3408** [Comp231-S4G5/OneClickCleaner#3]
- [x]  Create an Emergency form detail where it will be displayed a mandatory input that allows the customer to choose a desired duration of the service between 1 to 6 #39 

- [x] Call to a function “calculate total price” to calculate the price based on the duration and display the total inside the emergency form. #53
- [x] Create a new order in the database and save the first details of it and the cleaner will be choose automatically #37
