### ISSUE TITLE
As a Client, I want to see the booking page so that I can either choose the desired location, see more specific details about the booking service, choose the desired day, choose the time period of the service.

### ISSUE THREAD

**Issue by rmc3408** [Comp231-S4G5/OneClickCleaner#4]
- [x] Add a text with service details #41 

- [x] Create a dropdown list for choosing the time - for periods such as morning, afternoon, evening, and night. #43

- [x] Add a calendar that the user can choose a day (min 48 hours and max 100 days), if not display an error message. #61

- [x]  Display an error message if the client does not fill out all the fields (validation). #65

- [x] Display a successful message and a button to procceds to next step #66

**Comment by rmc3408** [comment]
![image](https://user-images.githubusercontent.com/64808456/99284419-3d65e400-2804-11eb-933b-4ff7bd4e2f58.png)

**Comment by ajlanlien** [comment]
Display an error message if the client does not fill out all the fields (validation).

**Comment by ajlanlien** [comment]
Display and error message if the client does not fill out all the fields (validation)

**Comment by ajlanlien** [comment]
hello
