### ISSUE TITLE
As Client, I want to see the booking page so that I can choose the duration of service and see the available price.

### ISSUE THREAD

**Issue by rmc3408** [Comp231-S4G5/OneClickCleaner#5]
- [x] Create a booking form where it will be displayed a mandatory input that allows customer to choose a duration between 1 to 6 (hours). #45 

- [x] Call a function “Calculate booking total price” to calculate the price based on the duration and display this price inside in the booking form. #55

- [x] Create a new order and save it in the database #67
