### ISSUE TITLE
The potential cleaner sees the application page so that I can enter and send my personal information.

### ISSUE THREAD

**Issue by rmc3408** [Comp231-S4G5/OneClickCleaner#7]
- [x] Create a form for the potential cleaner to fill out fields about the name, address, phone, email, and the number of the certification. #71

- [x] Create an error message in case the user does not fill out all required fields in the form (validation). #72

- [x] Create a submit button to send the information to the database #73
