### ISSUE TITLE
Administrator can create, read, update, and delete the cleaner account.

### ISSUE THREAD

**Issue by rmc3408** [Comp231-S4G5/OneClickCleaner#9]
- [x] Create a page for the Admin, where he/she can see the list of cleaners as well as some buttons such as add, delete, and edit cleaner. #44

- [x] Link the add button to the add new cleaner form page - build the add form page. #108

- [x] In the form page the Admin will fill all the cleaner’s details: Name, availability and location (GTA). #118

- [x] Create a button to edit and save cleaner information. #57

- [x] Create a function to retrieved cleaners’ information from the database. #85

- [x] Create an action linked to the delete button to delete the item selected - message of successful delete item. #46
