### ISSUE TITLE
As a Client, I do not need to choose the cleaner if I select Emergency Service so that I can proceed to the payment faster.

### ISSUE THREAD

**Issue by rmc3408** [Comp231-S4G5/OneClickCleaner#95]
- [x] Select automatically a service time based on the current timestamp and save it on the current order. #129

- [x] Create a function to select ONE cleaner from the list based on Location and availability. #97

- [x] Assign the selected cleaner to the order service #119

- [x] If no cleaner available, display a screen “service not available at the moment” #110

- [x] Save the selected cleaner in the ordering information before payment. #101
